name: Samaritan
main: net.samagames.samaritan.Samaritan
version: 3.0-SNAPSHOT
authors: [Thog]
website: http://samagames.net/
depend: [SamaGamesAPI, ShadowsAPI]

commands:
   samaritan:
      description: The best Global Security System