name: AntiCheat
main: net.samagames.anticheat.AntiCheat
version: 1.0.0
authors: [zyuiop, Geekpower14]
website: http://samagames.net/
depend: [MasterBundle]
commands:
   anticheat:
      description: Main anticheat commands